New rocAL python API
LakshmiKumar23/MIVisionX pull request #9
Opened 2021-10-22 16:15 UTC by swetha097

1. Augmentation App
2. coco pipeline
3. caffe, caffe2 pipelines for classification & detection
4. tf classification & detection pipeline
5. python rali unit test

2021-10-22 16:32 UTC, LakshmiKumar23 requested changes
@swetha097 I also see a couple of empty files. Are they needed?

2021-10-22 16:32 UTC, LakshmiKumar23 commented on rocAL/rocAL/source/master_graph.cpp
> +THE SOFTWARE.lround
@swetha097 Can you check what this is. Seems like a typo?

2021-10-22 16:32 UTC, LakshmiKumar23 commented on rocAL/rocAL/source/rali_api_data_loaders.cpp
> +    std::cout<<"\n COMES TO COCOFILESOURCESINGLESHARD";
@swetha097 Do we need the debug statements? Same above?

2021-10-22 17:01 UTC, rrawther commented on rocAL/rocAL/source/rali_api_augmentation.cpp
> +    std::cerr<<"\n**************************************************************************";
I think this should be removed

2021-10-22 17:17 UTC, rrawther reviewed
@swetha097  need to review this

2021-10-25 13:08 UTC, swetha097 commented on rocAL/rocAL/source/rali_api_augmentation.cpp
> +    std::cerr<<"\n**************************************************************************";
Done

2021-10-25 13:08 UTC, swetha097 commented on rocAL/rocAL/source/rali_api_data_loaders.cpp
> +    std::cout<<"\n COMES TO COCOFILESOURCESINGLESHARD";
Removed the debug statement

2021-10-25 13:09 UTC, swetha097 commented on rocAL/rocAL/source/master_graph.cpp
> +THE SOFTWARE.lround
I think its a typo Lakshmi.
Removed it

2022-04-25 22:48 UTC, closed without merging